services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=feature
    ports:
      - 5432:5432
    networks:
      - feature-net

networks:
  feature-net: